# Generated by Django 5.1.1 on 2024-10-14 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=100)),
                ('ticket_type', models.CharField(choices=[('VI', 'VISITOR'), ('ORG', 'ORGANIZER'), ('GLD', 'GOLD'), ('VIP', 'VIP')], max_length=3)),
                ('price', models.PositiveIntegerField()),
                ('availability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VI', 'VISITOR'), ('ORG', 'ORGANIZER')], max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=100)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_organizer', to='EventBookingApp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('event_booked_by_cust', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event_booked_by_cust', to='EventBookingApp.events')),
                ('user_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_type', to='EventBookingApp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_by', to=settings.AUTH_USER_MODEL)),
                ('event_booked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_booked', to='EventBookingApp.events')),
                ('ticket_booked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_booked', to='EventBookingApp.tickets')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event_booked', 'ticket_booked'), name='unique-booking')],
            },
        ),
    ]
