# Generated by Django 5.1.1 on 2024-10-14 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventBookingApp', '0002_remove_customer_event_booked_by_cust_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='organizer_profile',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='ticket_number',
        ),
        migrations.AddField(
            model_name='tickets',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event_for_ticket', to='EventBookingApp.events'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_by', to='EventBookingApp.userprofile'),
        ),
        migrations.AlterField(
            model_name='events',
            name='organizer',
            field=models.ForeignKey(limit_choices_to={'type': 'ORG'}, on_delete=django.db.models.deletion.CASCADE, related_name='event_organizer', to='EventBookingApp.userprofile'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
    ]
