# Generated by Django 5.1.1 on 2024-10-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventBookingApp', '0003_remove_organizer_organizer_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
