# Generated by Django 5.1.1 on 2024-10-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventBookingApp', '0004_tickets_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='ticket_type',
            field=models.CharField(choices=[('NOR', 'NORMAL'), ('SIL', 'SILVER'), ('GLD', 'GOLD'), ('VIP', 'VIP')], max_length=3),
        ),
    ]
