# Generated by Django 5.1.1 on 2024-10-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventBookingApp', '0006_tickets_unique_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_num',
            field=models.PositiveBigIntegerField(default=None),
        ),
    ]
