# Generated by Django 5.1.1 on 2024-10-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventBookingApp', '0010_alter_userprofile_contact_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_num',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
