# Generated by Django 5.1.1 on 2024-10-15 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventBookingApp', '0012_alter_userprofile_contact_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_num',
        ),
    ]
